//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dict
    {
        public string id { get; set; }
        public string value { get; set; }
        public string label { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public int sort { get; set; }
        public string parent_id { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string remarks { get; set; }
        public int del_flag { get; set; }
    }
}
