//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Member_Coupon_Account = new HashSet<Member_Coupon_Account>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone_num { get; set; }
        public string wechat_no { get; set; }
        public string password { get; set; }
        public int type { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> superior_agent_id { get; set; }
        public string pic_path { get; set; }
        public string card_holder { get; set; }
        public string card_no { get; set; }
        public string deposit_bank { get; set; }
        public string deposit_branch_bank { get; set; }
        public System.DateTime reg_time { get; set; }
        public Nullable<System.DateTime> settle_time { get; set; }
        public Nullable<int> total_point { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int secret_status { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> month_rebate_time { get; set; }
        public int app_browse_count { get; set; }
        public int product_browse_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Coupon_Account> Member_Coupon_Account { get; set; }
        public virtual Member Superior_Agent { get; set; }
    }
}
