//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Coupon_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member_Coupon_Account()
        {
            this.Product_Order_Detail = new HashSet<Product_Order_Detail>();
        }
    
        public int id { get; set; }
        public int member_id { get; set; }
        public int is_use { get; set; }
        public Nullable<System.DateTime> use_time { get; set; }
        public int coupon_id { get; set; }
        public System.DateTime create_time { get; set; }
    
        public virtual Coupon_Info Coupon_Info { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order_Detail> Product_Order_Detail { get; set; }
    }
}
