//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Browse_Statistics
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> total_count { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
