//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Micro_Class_Info
    {
        public int id { get; set; }
        public int group_id { get; set; }
        public string topic_info_title { get; set; }
        public string lecturer_text { get; set; }
        public string mp3_url { get; set; }
        public Nullable<int> mp3_duration { get; set; }
        public string img_url { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    
        public virtual Micro_Class_Group Micro_Class_Group { get; set; }
    }
}
