//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point_Exchange_Record
    {
        public int id { get; set; }
        public int point_exchange_id { get; set; }
        public int point_exchange_status { get; set; }
        public string modify_comment { get; set; }
        public int modify_user_id { get; set; }
        public System.DateTime modify_date_time { get; set; }
    
        public virtual Point_Exchange Point_Exchange { get; set; }
        public virtual User Modify_User { get; set; }
    }
}
