//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Order_Master()
        {
            this.Order_Rebate_New = new HashSet<Order_Rebate_New>();
            this.Product_Order_Detail = new HashSet<Product_Order_Detail>();
            this.Product_Order_Record = new HashSet<Product_Order_Record>();
        }
    
        public string id { get; set; }
        public int member_id { get; set; }
        public string consignee { get; set; }
        public string consignee_address { get; set; }
        public string consignee_phone { get; set; }
        public decimal real_total_price { get; set; }
        public decimal order_price { get; set; }
        public int product_num { get; set; }
        public int current_status { get; set; }
        public string transport_no { get; set; }
        public string transport_company { get; set; }
        public System.DateTime order_date_time { get; set; }
        public Nullable<System.DateTime> order_complete_time { get; set; }
        public Nullable<System.DateTime> payment_date_time { get; set; }
        public Nullable<System.DateTime> rebate_date_time { get; set; }
        public Nullable<System.DateTime> refund_date_time { get; set; }
        public int rebate_flag { get; set; }
        public int del_flag { get; set; }
        public int total_Rebate_Amount { get; set; }
        public int superior_Rebate_Amount { get; set; }
        public int superior_Parent_Rebate_Amount { get; set; }
        public decimal receiving_real_price { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Rebate_New> Order_Rebate_New { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order_Detail> Product_Order_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order_Record> Product_Order_Record { get; set; }
        public virtual Product_Order_Master Product_Order_Master1 { get; set; }
        public virtual Product_Order_Master Product_Order_Master2 { get; set; }
    }
}
