//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Info()
        {
            this.Product_Anti_Fake = new HashSet<Product_Anti_Fake>();
            this.Product_Pictures = new HashSet<Product_Pictures>();
            this.Product_Attribute = new HashSet<Product_Attribute>();
            this.Product_Category = new HashSet<Product_Category>();
            this.Product_Group = new HashSet<Product_Group>();
        }
    
        public int id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string summary { get; set; }
        public string thumb_pic { get; set; }
        public string desc_url { get; set; }
        public decimal cost_price { get; set; }
        public decimal real_price { get; set; }
        public decimal first_distribution_price { get; set; }
        public decimal second_distribution_price { get; set; }
        public decimal member_price { get; set; }
        public int sales_num { get; set; }
        public int stock { get; set; }
        public int status { get; set; }
        public int serial_no { get; set; }
        public System.DateTime create_date_time { get; set; }
        public Nullable<System.DateTime> modify_date_time { get; set; }
        public Nullable<int> modify_user_id { get; set; }
        public int browse_count { get; set; }
        public int star_white { get; set; }
        public int star_granularity { get; set; }
        public int star_defect { get; set; }
        public int star_oily { get; set; }
        public string pic_url { get; set; }
        public string video_url { get; set; }
    
        public virtual Member Modify_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Anti_Fake> Product_Anti_Fake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Pictures> Product_Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Attribute> Product_Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Category> Product_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Group> Product_Group { get; set; }
        public virtual User User { get; set; }
    }
}
