//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Anti_Fake
    {
        public int id { get; set; }
        public string product_thumb_pic { get; set; }
        public string product_pictures { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public string product_summary { get; set; }
        public int product_star_white { get; set; }
        public int product_star_granularity { get; set; }
        public int product_star_defect { get; set; }
        public int product_star_oily { get; set; }
        public Nullable<int> product_id { get; set; }
        public int status { get; set; }
        public System.DateTime create_time { get; set; }
        public string product_qrcode_path { get; set; }
    
        public virtual Product_Info Product_Info { get; set; }
    }
}
