//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order_Detail
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string thumb_pic { get; set; }
        public int buy_num { get; set; }
        public string summary { get; set; }
        public string desc_url { get; set; }
        public string cert_sign { get; set; }
        public decimal current_price { get; set; }
        public decimal cost_price { get; set; }
        public decimal real_price { get; set; }
        public decimal first_distribution_price { get; set; }
        public decimal second_distribution_price { get; set; }
        public decimal member_price { get; set; }
        public int is_receiving { get; set; }
        public int product_id { get; set; }
        public Nullable<int> coupon_id { get; set; }
        public string coupon_name { get; set; }
        public decimal coupon_sale_price { get; set; }
    
        public virtual Product_Info Product_Info { get; set; }
        public virtual Product_Order_Master Product_Order_Master { get; set; }
        public virtual Member_Coupon_Account Member_Coupon_Account { get; set; }
    }
}
