//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Push_Theme
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string theme_Url { get; set; }
        public int is_Delete { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
